### ISSUE TITLE
Error: WireGuard exited with the error: Cannot find device "wg0" This usually means that your host's kernel does not support WireGuard!

### ISSUE THREAD

**Issue by junlovejing** [wg-easy/wg-easy#1042]
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/lib/WireGuard.js:63:9
2024-05-16T14:57:45.973Z Server Listening on http://0.0.0.0:51821
2024-05-16T14:57:45.980Z WireGuard Loading configuration...
2024-05-16T14:57:45.983Z WireGuard Configuration loaded.
2024-05-16T14:57:45.984Z WireGuard Config saving...
2024-05-16T14:57:45.986Z WireGuard Config saved.

[root@centosserver ~]# uname -a
Linux centosserver 5.4.275-1.el7.elrepo.x86_64 #1 SMP Thu May 2 15:30:39 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

The kernel is the latest version 5.4.275
The docker is Restarting (1) 49 seconds ago

**Comment by m0x61h0x64i** [comment]
How solved?

**Comment by junlovejing** [comment]
Upgrading the kernel
