### ISSUE TITLE
[Bug]: wg-easy not working properly

### ISSUE THREAD

**Issue by hypereg** [wg-easy/wg-easy#1362]
### Describe the bug

Im literally installing on clean ubuntu 22.04 only what im do is apt update,upgrade and then install docker and execute this command:
 docker run -d \
  --name=wg-easy \
  -e LANG=de \
  -e WG_HOST=xx.xxx.xx.xxx  \
  -e PASSWORD_HASH=xxxxx \
  -e PORT=51821 \
  -e WG_PORT=51820 \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  ghcr.io/wg-easy/wg-easy
  
  and i got 
  Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!

### Expected behavior

I want to it works :D

### Relevant log output

```shell
root@server-1715741-1:~# docker logs b708203e31dc

2024-09-06T09:53:43.972Z Server Listening on http://0.0.0.0:51821
2024-09-06T09:53:43.977Z WireGuard Loading configuration...
$ wg genkey
$ echo ***hidden*** | wg pubkey
2024-09-06T09:53:43.999Z WireGuard Configuration generated.
2024-09-06T09:53:44.000Z WireGuard Config saving...
2024-09-06T09:53:44.003Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:74:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WireGuard.getConfig (/app/lib/WireGuard.js:72:7)
2024-09-06T09:54:01.478Z Server Listening on http://0.0.0.0:51821
2024-09-06T09:54:01.487Z WireGuard Loading configuration...
2024-09-06T09:54:01.492Z WireGuard Configuration loaded.
2024-09-06T09:54:01.492Z WireGuard Config saving...
2024-09-06T09:54:01.494Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:74:17
    at async WireGuard.getConfig (/app/lib/WireGuard.js:72:7)
2024-09-06T09:54:16.779Z Server Listening on http://0.0.0.0:51821
2024-09-06T09:54:16.786Z WireGuard Loading configuration...
2024-09-06T09:54:16.792Z WireGuard Configuration loaded.
2024-09-06T09:54:16.793Z WireGuard Config saving...
2024-09-06T09:54:16.798Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:74:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WireGuard.getConfig (/app/lib/WireGuard.js:72:7)
root@server-1715741-1:~#
```

**Comment by eandersons** [comment]
[Cannot find device "wg0"](/wg-easy/wg-easy/issues?q=is%3Aissue+Cannot+find+device+%22wg0%22)

**Comment by hypereg** [comment]
> [Cannot find device "wg0"](/wg-easy/wg-easy/issues?q=is%3Aissue+Cannot+find+device+%22wg0%22)

which version of kernel should be ok? 
i have
root@server-1715741-1:~# uname -a
Linux server-1715741-1 5.2.0 #1 SMP Wed Jul 12 12:00:44 MSK 2023 x86_64 x86_64 x86_64 GNU/Linux
root@server-1715741-1:~#

**Comment by kaaax0815** [comment]
@hypereg 
Please run following commands
```sh
  uname -a
  lsb_release -a
```
and post the full result

**Comment by hypereg** [comment]
root@server-1715741-1:~#   uname -ame -a
Linux server-1715741-1 5.2.0 #1 SMP Wed Jul 12 12:00:44 MSK 2023 x86_64 x86_64 x86_64 GNU/Linux
root@server-1715741-1:~#   lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
root@server-1715741-1:~#

**Comment by kaaax0815** [comment]
You have an extremely old kernel for some reason. Wireguard is supported since `5.6`[^1]. I am running Ubuntu 22.04 aswell and I am on Kernel `5.15.0`

[^1]: https://www.xda-developers.com/wireguard-vpn-linux-kernel-5-6/
