### ISSUE TITLE
New Docker fails to start

### ISSUE THREAD

**Issue by gsmith28** [wg-easy/wg-easy#490]
**Describe the bug**
Deployed using the docker run command and there is an error in the log and the ui does not start.  I have tried on multiple different docker hosts to the same result.

This fails on the command : wg-quick up wg0

[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}
2023-02-18T01:04:08.868Z Server Listening on http://0.0.0.0:51821
2023-02-18T01:04:08.872Z WireGuard Loading configuration...
2023-02-18T01:04:08.879Z WireGuard Configuration loaded.
2023-02-18T01:04:08.880Z WireGuard Config saving...
2023-02-18T01:04:08.888Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}
2023-02-18T01:04:14.536Z Server Listening on http://0.0.0.0:51821
2023-02-18T01:04:14.540Z WireGuard Loading configuration...
2023-02-18T01:04:14.549Z WireGuard Configuration loaded.
2023-02-18T01:04:14.550Z WireGuard Config saving...
2023-02-18T01:04:14.560Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}
2023-02-18T01:04:23.372Z Server Listening on http://0.0.0.0:51821
2023-02-18T01:04:23.376Z WireGuard Loading configuration...
2023-02-18T01:04:23.383Z WireGuard Configuration loaded.
2023-02-18T01:04:23.384Z WireGuard Config saving...
2023-02-18T01:04:23.391Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0
    at ChildProcess.exithandler (child_process.js:383:12)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  killed: false,
  code: 3,
  signal: null,
  cmd: 'wg-quick up wg0'
}

**Comment by ojarosch** [comment]
Same here.
Additional Info:

```
Operating System: AlmaLinux 9.1 (Lime Lynx)           
Kernel: Linux 5.14.0-162.12.1.el9_1.aarch64
```

Running `wg-quick up wg0` natively works.

EDIT: followed recommendation from https://github.com/wg-easy/wg-easy/issues/290#issuecomment-1159465924. Now it works

Edit No2: Updated link to honor renaming of repo owner

**Comment by dopeh** [comment]
> Same here. Additional Info:
> 
> ```
> Operating System: AlmaLinux 9.1 (Lime Lynx)           
> Kernel: Linux 5.14.0-162.12.1.el9_1.aarch64
> ```
> 
> Running `wg-quick up wg0` natively works.
> 
> EDIT: followed recommendation from https://github.com/WeeJeWel/wg-easy/issues/290#issuecomment-1159465924. Now it works

@ojarosch can you repeat those instructions here since the referenced issue is no longer accessible. Thanks!

**Comment by chuyendoithuong** [comment]
> > Same here. Additional Info:
> > ```
> > Operating System: AlmaLinux 9.1 (Lime Lynx)           
> > Kernel: Linux 5.14.0-162.12.1.el9_1.aarch64
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Running `wg-quick up wg0` natively works.
> > EDIT: followed recommendation from https://github.com/WeeJeWel/wg-easy/issues/290#issuecomment-1159465924. Now it works
> 
> @ojarosch can you repeat those instructions here since the referenced issue is no longer accessible. Thanks!

@dopeh I did the following simple step to get it working (reboot after run command)
`echo ip_tables > /etc/modules-load.d/ip_tables.conf`

**Comment by jmarmstrong1207** [comment]
> [@dopeh](https://github.com/dopeh) I did the following simple step to get it working (reboot after run command) `echo ip_tables > /etc/modules-load.d/ip_tables.conf`

Just wanted to update for google searchers, loading ip_tables module to the kernel fixed it. Fedora Server didn't have it by default for some reason.

I also did `modprobe ip_tables` so i dont need to restart
