### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by devparadigma** [wg-easy/wg-easy#518]
OS:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

`docker run -d \
  --name=wg-easy \
  -e WG_HOST=XXXXXXXXX \
  -e PASSWORD=XXXXXXXX \
  -v ~/.wg-easy:/etc/wireguard \
  -p 51820:51820/udp \
  -p 51821:51821/tcp \
  --cap-add=NET_ADMIN \
  --cap-add=SYS_MODULE \
  --sysctl="net.ipv4.conf.all.src_valid_mark=1" \
  --sysctl="net.ipv4.ip_forward=1" \
  --restart unless-stopped \
  weejewel/wg-easy`

I must say right away that installing wireguard and wireguard-tools does not help!

===========================================================
LOGS:
docker logs -f d85f3d7a5da1d3872e4e30102168337e102d4ab6cd11fc95154b54b2efdccb6e
2023-03-29T10:58:38.682Z Server Listening on http://0.0.0.0:51821
2023-03-29T10:58:38.683Z WireGuard Loading configuration...
2023-03-29T10:58:38.684Z WireGuard Configuration loaded.
2023-03-29T10:58:38.684Z WireGuard Config saving...
2023-03-29T10:58:38.685Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at async /app/lib/WireGuard.js:63:9
2023-03-29T10:58:39.499Z Server Listening on http://0.0.0.0:51821
2023-03-29T10:58:39.499Z WireGuard Loading configuration...
2023-03-29T10:58:39.500Z WireGuard Configuration loaded.
2023-03-29T10:58:39.500Z WireGuard Config saving...
2023-03-29T10:58:39.501Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at async /app/lib/WireGuard.js:63:9
2023-03-29T10:58:40.400Z Server Listening on http://0.0.0.0:51821
2023-03-29T10:58:40.401Z WireGuard Loading configuration...
2023-03-29T10:58:40.402Z WireGuard Configuration loaded.
2023-03-29T10:58:40.402Z WireGuard Config saving...
2023-03-29T10:58:40.403Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at async /app/lib/WireGuard.js:63:9
2023-03-29T10:58:41.350Z Server Listening on http://0.0.0.0:51821
2023-03-29T10:58:41.351Z WireGuard Loading configuration...
2023-03-29T10:58:41.352Z WireGuard Configuration loaded.
2023-03-29T10:58:41.352Z WireGuard Config saving...
2023-03-29T10:58:41.353Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-03-29T10:58:42.775Z Server Listening on http://0.0.0.0:51821
2023-03-29T10:58:42.776Z WireGuard Loading configuration...
2023-03-29T10:58:42.777Z WireGuard Configuration loaded.
2023-03-29T10:58:42.777Z WireGuard Config saving...
2023-03-29T10:58:42.778Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at async /app/lib/WireGuard.js:63:9
2023-03-29T10:58:45.042Z Server Listening on http://0.0.0.0:51821
2023-03-29T10:58:45.043Z WireGuard Loading configuration...
2023-03-29T10:58:45.044Z WireGuard Configuration loaded.
2023-03-29T10:58:45.044Z WireGuard Config saving...
2023-03-29T10:58:45.045Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
2023-03-29T10:58:49.327Z Server Listening on http://0.0.0.0:51821
2023-03-29T10:58:49.328Z WireGuard Loading configuration...
2023-03-29T10:58:49.329Z WireGuard Configuration loaded.
2023-03-29T10:58:49.329Z WireGuard Config saving...
2023-03-29T10:58:49.329Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at async /app/lib/WireGuard.js:63:9

**Comment by Regis-Loyaute** [comment]
your issue is not related with wg-easy

**Comment by Jobba7** [comment]
I have the same issue on my pi 4

**Comment by borekon** [comment]
Follow these steps: https://www.cyberciti.biz/faq/debian-10-set-up-wireguard-vpn-server/
Then reboot and try again and...voilà! It works

**Comment by wokalek** [comment]
> Follow these steps: https://www.cyberciti.biz/faq/debian-10-set-up-wireguard-vpn-server/ Then reboot and try again and...voilà! It works

Just apt-get update & upgrade solved my problem, thanks!
