### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by utlimate** [wg-easy/wg-easy#818]
Facing en error  while installing without docker

ubuntu@downloader:/app$ /usr/bin/env node /app/server.js
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:crypto'
Require stack:
- /app/lib/Server.js
- /app/services/Server.js
- /app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/lib/Server.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/lib/Server.js', '/app/services/Server.js', '/app/server.js' ]
}

**Comment by pheiduck** [comment]
What’s your node.js version? Older ones behind 18.x use crypto. And this project is based on node.js 18 so you might need to upgrade your node.js  to 18.x or newer.

**Comment by pheiduck** [comment]
Wiki Page is updated as well: https://github.com/wg-easy/wg-easy/wiki/Using-WireGuard-Easy-without-Docker
