### ISSUE TITLE
Not Able to create new clients

### ISSUE THREAD

**Issue by javedh-dev** [wg-easy/wg-easy#913]
**Describe the bug**
This bug is in the latest release which introduced `uiTrafficStats` environment variabke

**To Reproduce**
1. Install latest version using docker
2. Add a new client

**Expected behavior**
The client must be added and should be visible in the list
**Screenshots**
![Screenshot 2024-03-14 082056](https://github.com/wg-easy/wg-easy/assets/21221044/80bfb1f8-b7e4-4a0b-8210-1cfa729e0416)
![Screenshot 2024-03-14 082107](https://github.com/wg-easy/wg-easy/assets/21221044/0d2f902d-4c66-451f-8152-51a0ee55dbe6)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser MS Edge
 - Version latest

**Smartphone (please complete the following information):**
Not relevent

**Additional context**
It's happening due to following error - 
```
vue.min.js:6  ReferenceError: uiTrafficStats is not defined
    at eval (eval at mc (vue.min.js:6:105188), <anonymous>:3:9044)
    at Er.ce [as _l] (vue.min.js:6:13080)
    at Er.eval (eval at mc (vue.min.js:6:105188), <anonymous>:3:2812)
    at t._render (vue.min.js:6:45862)
    at Er.r (vue.min.js:6:79765)
    at t.get (vue.min.js:6:28262)
    at t.run (vue.min.js:6:28995)
    at cn (vue.min.js:6:19867)
    at Array.<anonymous> (vue.min.js:6:23307)
    at Sn (vue.min.js:6:22707)
```

**Comment by pheiduck** [comment]
We had to rebuild the last 2 release please pull the image again

**Comment by javedh-dev** [comment]
Thanks it's working now.
